### ISSUE TITLE
No map is displayed

### ISSUE THREAD

**Issue by JLD95** [bymaximus/msfs2020-toolbar-little-nav-map#1]
Hi, I just downloaded the toolbar but no map is displayed. I have steam version installed under (E:\Microsoft Flight Simulator\Community\fs-base-ingamepanels-lnm) and LNM is under C:\Users\Jean-Luc\AppData\Roaming\ABarthel\little_navmap_db.

See test on LFPG

![2020-10-11 (33)](https://user-images.githubusercontent.com/5894146/95678270-daad7700-0bcb-11eb-885f-fe4053af2b12.png)

Nota: LNM standalone works fine with FSUIPC7

![2020-10-11 (34)](https://user-images.githubusercontent.com/5894146/95678258-c79aa700-0bcb-11eb-973c-7f10150b9c54.png)

**Comment by bymaximus** [comment]
Did you enabled LNM webserver?

**Comment by JLD95** [comment]
Hi, no I don't know how to enable server? It's a parameter of LNM standalone? In the readme, no mention to install and parameterize LNM

**Comment by bymaximus** [comment]
The readme says it uses LNM webserver, you need to enable it in the LNM options
https://github.com/bymaximus/msfs2020-toolbar-little-nav-map/blob/daf135b0f7443cb674685ea7a9db2506e24499f8/README.md#L2

[https://www.littlenavmap.org/manuals/littlenavmap/release/2.4/en/WEBSERVER.html?highlight=webserver](url)

**Comment by JLD95** [comment]
Thanks, it works now
