### ISSUE TITLE
Browser Toolbar

### ISSUE THREAD

**Issue by nicetoTECHyou** [bymaximus/msfs2020-toolbar-little-nav-map#4]
Hey .. is it Possible that you can create a Toolbar with a Text field to enter a IP or a www Adress ? :D i try it with the template and change only the Skyvector adress and it does not work :D 

or do you have soo much Knowledge to bring a Youtube Funktion on a Garmin Display inside my Plane ? :D 

sry that i write here .. i dont find a PM Button on Github

**Comment by bymaximus** [comment]
Not every website can be loaded from an iFrame, skyvector for example can’t like before.
