### ISSUE TITLE
Add support for zooming the map

### ISSUE THREAD

**Issue by neilenns** [bymaximus/msfs2020-toolbar-little-nav-map#5]
I *love* this extension. It's so simple but so useful for VFR flights. One thing I'd love to have added: ability to zoom the map. This would be super handy when I'm flying into an unfamiliar airport and want to see nearby roads/landmarks.

**Comment by bymaximus** [comment]
The zoom have been already added.

[https://github.com/bymaximus/msfs2020-toolbar-little-nav-map/commit/07b869ad3ea403d8b06b99f2a202e27390a3a932](url)

**Comment by neilenns** [comment]
Was this released in an update recently? I don't see any zoom UI. Maybe for future releases you can use the github releases feature so people can subscribe to notifications for new stuff? Thanks!
