### ISSUE TITLE
Empty Map

### ISSUE THREAD

**Issue by vmoins7212** [bymaximus/msfs2020-toolbar-little-nav-map#8]
Hello. I've just installed this add-on in MSFS 2020 today. I've extracted the zip in my Community folder as required. When I start a fly, I see the little navmap button in the toolbar, when I click on in, the window is displayed but it remains empty with a kind of "loading" circle icon in its center. 
The official little navmap application is started and is connected to the simulator since I can see and follow my plane there, but the map in the game is empty.
I'm using the last 2.6.6 stable version of Little Navmap.

**Comment by bymaximus** [comment]
Did you enabled lnm webserver?

**Comment by vmoins7212** [comment]
Hello. Sorry I did not see your answer. What do you mean by enabling lnm webserver ?

**Comment by bymaximus** [comment]
To use this addon, you must enable LittleNavMap webserver at options.

[https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/OPTIONS.html#web-server-web-server](url)

![image](https://user-images.githubusercontent.com/595991/104528856-126ef500-55e7-11eb-89c6-c4f97afb98f7.png)
